# Generated by Django 4.0.2 on 2023-02-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
