# Generated by Django 4.0.2 on 2023-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_patient_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otp',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
