# Generated by Django 4.0.2 on 2023-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_feedback_on_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='Profile.png', upload_to=''),
        ),
    ]
