# Generated by Django 4.0.2 on 2023-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='name',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
