# Generated by Django 4.0.2 on 2023-03-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_status_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='number_of_product',
        ),
    ]
