# Generated by Django 4.0.2 on 2023-03-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('license_number', models.CharField(max_length=15)),
                ('issue_authority_name', models.CharField(max_length=1000)),
                ('specialist', models.CharField(max_length=500)),
                ('experience', models.IntegerField(max_length=2)),
                ('aadhar_card_number', models.CharField(max_length=12)),
                ('otp', models.IntegerField(default=None, null=True)),
                ('is_authorize', models.BooleanField(default=False)),
                ('has_bankdetails', models.BooleanField(default=False)),
                ('has_hospitaldetails', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(default='Profile.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=1024)),
                ('ifsc_code', models.CharField(max_length=1024)),
                ('upi_id', models.CharField(default=None, max_length=1024)),
                ('account_number', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bank', to='Doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress1', models.CharField(max_length=2000)),
                ('adress2', models.CharField(max_length=2000)),
                ('Building_Number', models.IntegerField()),
                ('zip_code', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('state', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=2000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_address', to='Doctor.doctor')),
            ],
        ),
    ]
