# Generated by Django 4.0.2 on 2023-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.CharField(default=None, max_length=10000),
            preserve_default=False,
        ),
    ]
