# Generated by Django 4.0.2 on 2023-04-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctor_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialist', to='Doctor.specilization'),
        ),
    ]
