# Generated by Django 4.0.2 on 2023-04-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_specilization_alter_doctor_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('description', models.CharField(max_length=1000000)),
                ('is_apporved', models.BooleanField(default=False)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_blogs', to='Doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='BlogsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('blogs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs_image_model', to='Doctor.blogs')),
            ],
        ),
    ]
